# Generated by Django 6.0.2 on 2026-06-26 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_media_processing_and_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_convers_3a8f50_idx',
            old_name='chat_messag_conversa_8b51e7_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_convers_bf492e_idx',
            old_name='chat_messag_conversa_7a0be6_idx',
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_deleted', 'created_at'], name='chat_conver_is_dele_bc37c9_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'timestamp'], name='chat_messag_convers_cd68de_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'timestamp'], name='chat_messag_sender__b20cde_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type'], name='chat_messag_message_973666_idx'),
        ),
    ]
