# Generated by Django 6.0.2 on 2026-06-26 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
